---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-ts-api
  template:
    metadata:
      labels:
        app: node-ts-api
    spec:
      containers:
        - name: nodetsapi
          imagePullPolicy: IfNotPresent
          image: node-ts-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: node-ts-api
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 3000
    selector:
        app: node-ts-api
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  location: canadaeast
  storageAccount: devdeveloperstorage
---
