---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-ts-api
  template:
    metadata:
      labels:
        app: node-ts-api
    spec:
      containers:
        - name: nodetsapi
          imagePullPolicy: IfNotPresent
          image: devdeveloperregistry.azurecr.io/node-ts-api:0 # {"$imagepolicy": "flux-system:node-ts-api"} <=== add this comment and change intial tag
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: node-ts-api
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 3000
    selector:
        app: node-ts-api
---
